# Generated by Django 3.2.25 on 2024-12-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='images',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='collaborations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='influences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='styles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='techniques',
            field=models.TextField(blank=True),
        ),
    ]
