# Generated by Django 3.2.25 on 2025-01-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20241223_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../user_vwophi', upload_to='images/'),
        ),
    ]
