# Generated by Django 3.2.25 on 2024-12-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='type',
            field=models.CharField(choices=[('Collage', 'Collage'), ('Drawing', 'Drawing'), ('Needlework', 'Needlework'), ('Etching', 'Etching'), ('Painting', 'Painting'), ('Photography', 'Photography'), ('Pottery', 'Pottery'), ('Sculpture', 'Sculpture'), ('Watercolour', 'Watercolour'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
