# Generated by Django 3.2.25 on 2024-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_artwork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, default='../default_artwork_vrmnym', upload_to='images/'),
        ),
    ]
