# Generated by Django 3.2.25 on 2025-01-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20250101_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(default='Unknown artist', max_length=250),
        ),
    ]
