# Generated by Django 3.2.25 on 2024-12-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
    ]
