# Generated by Django 3.2.25 on 2024-12-10 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_artwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='phone',
        ),
    ]
