# Generated by Django 3.2.25 on 2024-12-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_bid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
